# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  trellis.kookacreative.com.au:
    site_hosts:
      - canonical: trellis.com.au
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: luca@kookacreative.com.au
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
